name: deployworkflow
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v3.0
    - name: install dependencies
      run: npm ci
    - name: lint
      run: npm lint
    - name: test
      run: npm test
    - name: build
      run: npm build
    - name: deploy
      run: echo  "deploying"
